import Joi from 'joi';

export const MiniCognitionSchema = Joi.object({
  checked1_1: Joi.boolean().required(),
  checked1_2: Joi.boolean().required(),
  checked1_3: Joi.boolean().required(),
  checked1_4: Joi.boolean().required(),
  checked1_5: Joi.boolean().required(),
  checked2_1: Joi.boolean().required(),
  checked2_2: Joi.boolean().required(),
  checked2_3: Joi.boolean().required(),
  checked2_4: Joi.boolean().required(),
  checked2_5: Joi.boolean().required(),
  checked3_1: Joi.boolean().required(),
  checked3_2: Joi.boolean().required(),
  checked3_3: Joi.boolean().required(),
  checked4_1: Joi.boolean().required(),
  checked4_2: Joi.boolean().required(),
  checked4_3: Joi.boolean().required(),
  checked4_4: Joi.boolean().required(),
  checked4_5: Joi.boolean().required(),
  checked5_1: Joi.boolean().required(),
  checked5_2: Joi.boolean().required(),
  checked5_3: Joi.boolean().required(),
  checked5_4: Joi.boolean().required(),
  checked5_5: Joi.boolean().required(),
  checked6_1: Joi.boolean().required(),
  checked6_2: Joi.boolean().required(),
  checked6_3: Joi.boolean().required(),
  checked7_1: Joi.boolean().required(),
  checked7_2: Joi.boolean().required(),
  checked8_1: Joi.boolean().required(),
  checked9_2: Joi.boolean().required(),
  checked9_1: Joi.boolean().required(),
  checked9_3: Joi.boolean().required(),
  checked10_1: Joi.boolean().required(),
  checked11_1: Joi.boolean().required(),
  checked12_1: Joi.boolean().required(),
  result: Joi.number().required()
}).options({
  abortEarly: false,
});